name: Migrate Work Items

on:
  workflow_dispatch:
    inputs: 
      ado-org:
        description: 'ado-org'
        required: true
        default: 'jjohanning0798'
      ado-project:
        description: 'ado-project'
        required: true
        default: 'PartsUnlimited'
      ado_area_path:
        description: 'ADO area path to migrate - uses the UNDER operator'
        required: true
        default: 'migrate'
      ado_migrate_closed_workitems:
        description: 'Migrate closed work items'
        required: true
        type: boolean
        default: 'true'
      ado_production_run:
        description: tag migrated work items with migrated-to-github and add discussion comment
        required: true
        type: boolean
        default: 'true'
      gh-org:
        description: 'gh-org'
        required: true
        default: 'joshjohanning-org'
      gh-repo:
        description: 'gh-org'
        required: true
        default: 'migrate-ado-workitems'
      gh_update_assigned_to:
        description: 'Update Assigned To'
        required: true
        type: boolean
        default: 'true'
      gh_assigned_to_user_suffix:
        description: 'EMU suffix'
        required: true
        default: '_corp'
      gh_add_ado_comments:
        description: 'Add ADO Comments'
        required: true
        type: boolean
        default: 'true'

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      
      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with: 
          app_id: 179484
          installation_id: 23995058
          private_key: "-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDr3L+b/1muc2aR
DiiCMr7j/8XDE4gUlOlbp+YrRvv41v9nrdrsYA8qFq85ZrB8e+ybD4NKHUFo41nK
/5arllLNtdmB9mFQn2cu6Ka4LPo/bHJAu5KY7GI+qwrqOIEtP8bBD/VAeQ7vksxM
LbCQmQyWx+3hROTc79mdgbfKAGBH590XXmMENWx4/VoqV9BMRDC75fsw8tICgsDK
PvJEA0JJA7QmxOwuYu1Ddq/wwe5T/IQHTQi+9Ilp3boJ9CswIjG1THIXNeqN6ztG
LbFCaOl0CBTLQyjZwDRATI+D+/AidHc/MS3A+jGhRvfUcFDV8fPW0PxJl4cI/O19
e5jaaFvbAgMBAAECggEAHSpm5ztkM5ZBkJ5XlAICaN8v7Td1FFZ1pMfWRnO4pMSx
QHjXIXOfbGzxrf9sw3fvgh0g9wE3HWk/qUKBtyYXhyh9hPyafAW6FKrgMtYc+8rF
Ngv7zL0uSOGNr/jcwGOqiCUZBqfxmN5mNOVReA/05pBCciC6zDc8iaWIvInfXgSp
IWOn5jMJv8oJIxkIjOrjbWw2mt6vnyjBp/w+Oei4W3zazIxdb2TMsgXXxAazzoDI
HJZwDgjzARgsfw7oA4CVAqjetxMAnU6K4iZeqz/KGmbaca127jl+Fx+f8zElFCc2
j29RHH6stl1JrW07VB+Ce/gII50rNYYE4TzipT9ZgQKBgQD67J0vwB805mlx6wZR
Rocl+LmTeDZDon+knfv4kV5kwzXdnpMBOW/3ToCRl5DiclWb3KgkPaY8RsfFX8Al
gq1UghcxkIj/chmc7FVv/iBFItPZrll02omcLVVML7mmsH/JyjXFakzwOPtl8vKY
u7JgVUvoQ/fPq6WB1TQSIrFdcwKBgQDwoiM2fh5OOkLBrCt5RlMkyD01tow1fM9H
HGguUiPowwyQvQntHM6xgiYT7ZVhInRoYEP0yk8G0VvH9Wea9LQGy6l1F63wZ+me
1aKnT/UTsfarDH1E8EorYyYLY+SFbINgK0GlH1bJ94VwsH+3jebq1djZh5qy+8E7
aYzmbdvt+QKBgQCvfoWBPBGXYf8lmYbVmUo0mHzSUyVAsIotjAEKnEE0oAMweRO/
q3hPsyvgp+zBM84EMJO4pRV62tYliQ5OLdMkY8fs9nWakyauxewLY+UV9YHNoU8X
lzDfdiVOH6Lsnk0ByNdKt0oQSQorB3v8rmnXTlDEpaTQLfCXmZHNjU4XWQKBgHxh
IlhhWiLPRIA9EP+PlRxXECR6ZgCjsbQs/8CpnnwKja0muUHBeSkRf8MfM+5QU+E7
mQSnqa95ebpio5nZ0FAO51lp0vOHkp8SCA/5aVEz1K9XNkzy8zN3/Us35//7NfD4
iubhywd8FJJJ+MoU4/4QaRUPXawUKy4dgcH9mQdpAoGAJNGpvynip3TcdIeizcml
M7QF95iu1Z/aBgexUCDCyAa0t/gFb7rbsta2aPNMkOzxr2ZnUO3mOl25il5G5MaK
8iyEAxfH9zkC/pSDazoF9cus/tjg2fzPVJ3lM7BFKlDSnpdDL2KViRAdQ9jHhGIH
T7C/wXQ/y8FNZAAbopznMG4=
-----END PRIVATE KEY-----"
      
      - name: run migration
        shell: pwsh
        run: |
          # run migration script
          
          # cleaning up bools
          $ado_migrate_closed_workitems=$false
          $ado_production_run=$false
          $gh_update_assigned_to=$false
          $gh_add_ado_comments=$false
          
          if("${{ github.event.inputs.ado_migrate_closed_workitems }}" -eq "true") {
            $ado_migrate_closed_workitems=$true
          }

          if("${{ github.event.inputs.ado_production_run }}" -eq "true") {
            $ado_production_run=$true
          }

          if("${{ github.event.inputs.gh_update_assigned_to }}" -eq "true") {
            $gh_update_assigned_to=$true
          }
          
          if("${{ github.event.inputs.gh_add_ado_comments }}" -eq "true") {
            $gh_add_ado_comments=$true
          }
          
          ./ado_workitems_to_github_issues.ps1 -ado_pat "${{ SECRETS.ADO_PAT }}" -ado_org "${{ github.event.inputs.ado-org }}" -ado_project "${{ github.event.inputs.ado-project }}" -ado_area_path "${{ github.event.inputs.ado_area_path }}" -ado_migrate_closed_workitems $ado_migrate_closed_workitems -ado_production_run $ado_production_run -gh_pat "${{ steps.get_installation_token.outputs.token }}" -gh_org "${{ github.event.inputs.gh-org }}" -gh_repo "${{ github.event.inputs.gh-repo }}" -gh_update_assigned_to $gh_update_assigned_to -gh_assigned_to_user_suffix "${{ github.event.inputs.gh_assigned_to_user_suffix }}" -gh_add_ado_comments $gh_add_ado_comments
          
