name: Migrate Work Items

on:
  workflow_dispatch:
    inputs: 
      ado-org:
        description: 'ado-org'
        required: true
        default: 'jjohanning0798'
      ado-project:
        description: 'ado-project'
        required: true
        default: 'PartsUnlimited'
      ado_area_path:
        description: 'ADO area path to migrate - uses the UNDER operator'
        required: true
        default: 'migrate'
      ado_migrate_closed_workitems:
        description: 'Migrate closed work items'
        required: true
        type: boolean
        default: 'true'
      ado_production_run:
        description: tag migrated work items with migrated-to-github and add discussion comment
        required: true
        type: boolean
        default: 'true'
      gh-org:
        description: 'gh-org'
        required: true
        default: 'joshjohanning-org'
      gh-repo:
        description: 'gh-org'
        required: true
        default: 'migrate-ado-workitems'
      gh_update_assigned_to:
        description: 'Update Assigned To'
        required: true
        type: boolean
        default: 'true'
      gh_assigned_to_user_suffix:
        description: 'EMU suffix'
        required: true
        default: '_corp'
      gh_add_ado_comments:
        description: 'Add ADO Comments'
        required: true
        type: boolean
        default: 'true'

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      
      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with: 
          app_id: 179484
          installation_id: 23995058
          private_key: ${-----BEGIN PRIVATE KEY----- MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC7VJTUt9Us8cKj MzEfYyjiWA4R4/M2bS1GB4t7NXp98C3SC6dVMvDuictGeurT8jNbvJZHtCSuYEvu NMoSfm76oqFvAp8Gy0iz5sxjZmSnXyCdPEovGhLa0VzMaQ8s+CLOyS56YyCFGeJZ qgtzJ6GR3eqoYSW9b9UMvkBpZODSctWSNGj3P7jRFDO5VoTwCQAWbFnOjDfH5Ulg p2PKSQnSJP3AJLQNFNe7br1XbrhV//eO+t51mIpGSDCUv3E0DDFcWDTH9cXDTTlR ZVEiR2BwpZOOkE/Z0/BVnhZYL71oZV34bKfWjQIt6V/isSMahdsAASACp4ZTGtwi VuNd9tybAgMBAAECggEBAKTmjaS6tkK8BlPXClTQ2vpz/N6uxDeS35mXpqasqskV laAidgg/sWqpjXDbXr93otIMLlWsM+X0CqMDgSXKejLS2jx4GDjI1ZTXg++0AMJ8 sJ74pWzVDOfmCEQ/7wXs3+cbnXhKriO8Z036q92Qc1+N87SI38nkGa0ABH9CN83H mQqt4fB7UdHzuIRe/me2PGhIq5ZBzj6h3BpoPGzEP+x3l9YmK8t/1cN0pqI+dQwY dgfGjackLu/2qH80MCF7IyQaseZUOJyKrCLtSD/Iixv/hzDEUPfOCjFDgTpzf3cw ta8+oE4wHCo1iI1/4TlPkwmXx4qSXtmw4aQPz7IDQvECgYEA8KNThCO2gsC2I9PQ DM/8Cw0O983WCDY+oi+7JPiNAJwv5DYBqEZB1QYdj06YD16XlC/HAZMsMku1na2T N0driwenQQWzoev3g2S7gRDoS/FCJSI3jJ+kjgtaA7Qmzlgk1TxODN+G1H91HW7t 0l7VnL27IWyYo2qRRK3jzxqUiPUCgYEAx0oQs2reBQGMVZnApD1jeq7n4MvNLcPv t8b/eU9iUv6Y4Mj0Suo/AU8lYZXm8ubbqAlwz2VSVunD2tOplHyMUrtCtObAfVDU AhCndKaA9gApgfb3xw1IKbuQ1u4IF1FJl3VtumfQn//LiH1B3rXhcdyo3/vIttEk 48RakUKClU8CgYEAzV7W3COOlDDcQd935DdtKBFRAPRPAlspQUnzMi5eSHMD/ISL DY5IiQHbIH83D4bvXq0X7qQoSBSNP7Dvv3HYuqMhf0DaegrlBuJllFVVq9qPVRnK xt1Il2HgxOBvbhOT+9in1BzA+YJ99UzC85O0Qz06A+CmtHEy4aZ2kj5hHjECgYEA mNS4+A8Fkss8Js1RieK2LniBxMgmYml3pfVLKGnzmng7H2+cwPLhPIzIuwytXywh 2bzbsYEfYx3EoEVgMEpPhoarQnYPukrJO4gwE2o5Te6T5mJSZGlQJQj9q4ZB2Dfz et6INsK0oG8XVGXSpQvQh3RUYekCZQkBBFcpqWpbIEsCgYAnM3DQf3FJoSnXaMhr VBIovic5l0xFkEHskAjFTevO86Fsz1C2aSeRKSqGFoOQ0tmJzBEs1R6KqnHInicD TQrKhArgLXX4v3CddjfTRJkFWDbE/CkvKZNOrcf1nhaGCPspRJj2KUkj1Fhl9Cnc dn/RsYEONbwQSjIfMPkvxF+8HQ== -----END PRIVATE KEY-----}
      
      - name: run migration
        shell: pwsh
        run: |
          # run migration script
          
          # cleaning up bools
          $ado_migrate_closed_workitems=$false
          $ado_production_run=$false
          $gh_update_assigned_to=$false
          $gh_add_ado_comments=$false
          
          if("${{ github.event.inputs.ado_migrate_closed_workitems }}" -eq "true") {
            $ado_migrate_closed_workitems=$true
          }

          if("${{ github.event.inputs.ado_production_run }}" -eq "true") {
            $ado_production_run=$true
          }

          if("${{ github.event.inputs.gh_update_assigned_to }}" -eq "true") {
            $gh_update_assigned_to=$true
          }
          
          if("${{ github.event.inputs.gh_add_ado_comments }}" -eq "true") {
            $gh_add_ado_comments=$true
          }
          
          ./ado_workitems_to_github_issues.ps1 -ado_pat "${{ SECRETS.ADO_PAT }}" -ado_org "${{ github.event.inputs.ado-org }}" -ado_project "${{ github.event.inputs.ado-project }}" -ado_area_path "${{ github.event.inputs.ado_area_path }}" -ado_migrate_closed_workitems $ado_migrate_closed_workitems -ado_production_run $ado_production_run -gh_pat "${{ steps.get_installation_token.outputs.token }}" -gh_org "${{ github.event.inputs.gh-org }}" -gh_repo "${{ github.event.inputs.gh-repo }}" -gh_update_assigned_to $gh_update_assigned_to -gh_assigned_to_user_suffix "${{ github.event.inputs.gh_assigned_to_user_suffix }}" -gh_add_ado_comments $gh_add_ado_comments
          
